modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="scriptbound"
version="${mod_version}"
displayName="ScriptBound Engine"
logoFile="icon.jpg"
authors="defend"
description='''
Map scripting engine for Minecraft 1.21.1 NeoForge.
'''

[[dependencies.scriptbound]]
modId="neoforge"
type="required"
versionRange="[21,)"
ordering="NONE"
side="BOTH"

[[dependencies.scriptbound]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"

[[dependencies.scriptbound]]
modId="blockbuster"
type="optional"
versionRange="*"
ordering="AFTER"
side="BOTH"
