modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''Map scripting engine for Minecraft 1.21.1 Forge. BBS integration is optional.'''
authors="defend"
logoFile="icon.jpg"

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="[51,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="blockbuster"
mandatory=false
versionRange="*"
ordering="AFTER"
side="BOTH"
